= Indentation and Claim Graphs
Indentation expresses relationships between claims without introducing a second document format. CAVE distinguishes qualifier children from continuation lines.

```cave
server CAUSE crash @ 80%
  WHEN load EXCEEDS 1000 req/s
  WHEN NOT cache/enabled
```

Qualifier children create edges from the parent claim to child claims. Typical edge roles are WHEN, UNLESS, BECAUSE, VIA, and QUALIFIES. They encode conditions and lineage while preserving each child as an independently stored claim.

```cave
monorepo CONTAINS packages/api
  CONTAINS packages/web
  CONTAINS packages/core
  PART-OF org/monorepos
```

Continuation lines inherit an endpoint from the parent and expand to sibling claims. An inverse continuation can place the inherited term in object position. The canonicalization phase resolves this before storage.

The resulting store is a graph of immutable claim rows plus explicit edge rows. Text is a readable tree projection of that graph; exports may restate a shared row when several parents cite it.


= Values, Units, Confidence, and Uncertainty
CAVE separates uncertainty in a measured value from uncertainty in belief. A numeric delta describes dispersion or tolerance in the value. Confidence describes the strength of evidence for the claim.

```cave
OpenAI HAS revenue: ~20B USD/yr +/- 2B USD/yr @2026-Q1 @ 90%
model HAS latency: 210ms +/- 15ms (1 sigma) @lab
```

The store keeps both raw value text and parsed numeric fields when possible. Multipliers such as K, M, and B normalize to ordinary numbers. Units remain explicit and comparisons require compatible units.

The probabilistic layer can fuse independent numeric estimates using precision-weighted averaging, with confidence acting as a weight. Conditional confidence can use noisy-AND: a claim at 80 percent conditioned on evidence at 60 percent yields 48 percent effective confidence when independence is an explicit assumption.

Competing hypotheses should normally be represented by different cause entities, not by repeatedly overwriting one opaque claim. Evidence then updates each hypothesis through new appends.

```cave
memory-leak CAUSE app/crash @ 50%
deadlock CAUSE app/crash @ 30%
oom-killer CAUSE app/crash @ 20%
```


= Time: Transaction and Valid Time
CAVE has two orthogonal time axes. Transaction time is generated by the store for every append and reconstructs what the store believed at a past boundary. Valid time is authored in the claim and describes when the fact applies in the modeled world.

```cave
jan WORKS-AT textile-mill @1950..1974
jan WORKS-AT railways @1975..
mill/wage IS 200 -> 900 PLN/mo @1950..1974
```

A time-range context uses two dots. Ranges may be closed or open-ended. A trajectory value uses two numeric endpoints and is interpolated linearly at query time. Timeless claims continue to match any valid-time query.

The CLI exposes transaction time with --as-of and valid time with --at. Because the filters compose, CAVE can answer questions such as: what did the store believe last year about the wage in 1962? No snapshots are required because all prior rows remain present.

```cave
cave query --db family.db "jan WORKS-AT ?where" --at 1960
cave query --db family.db "mill/wage IS" --at 1962
cave query --db family.db "mill/wage IS" --at 1962 --as-of 2025-12-31
```


= Append-Only Belief Evolution
The store never mutates a claim row. A new assessment appends a newer row in the same belief series. Current belief within a series is the row with the greatest transaction identifier.

```cave
Anthropic HAS ipo-timing: 2026-H2 @ 40%
Anthropic HAS ipo-timing: 2026-H2 @ 65% ; after CFO statement
Anthropic HAS ipo-timing: 2026-H2 @ 35% ; market worsened
```

The claim key defines which rows belong to one evolving fact. For a relation it includes canonical subject, verb, object, polarity, and non-source contexts. For an attribute claim, the value is outside the key so the property can change without becoming a different question.

Retraction is an append at zero confidence. Retraction removes current support but preserves the earlier assertion. Explicit negation is stronger and records the opposite proposition.

```cave
server IS compromised @ 0% ; retracted
server IS NOT compromised @ 90% ; clean forensic scan
```

Contradictions are legal at write time. CAVE does not impose global logical consistency because disagreements between sources, models, and human reviewers are often the knowledge that matters.


= Provenance and Source Stamping
Every append surface should identify who or what wrote a claim. Source provenance is represented by src-prefixed contexts, so it participates in claim identity and is queryable like any other context.

#table(columns: 2, inset: 5pt, stroke: 0.4pt + luma(190),
  [*Surface*],
  [*Typical stamp*],
  [Interactive CLI],
  [\@src:cli],
  [MCP append],
  [\@src:agent/<client>],
  [LLM ingest],
  [\@src:ingest],
  [Structured connector],
  [\@src:connect/<name>/<key>],
  [Rule conclusion],
  [\@src:rule/<id>],
  [Action effect],
  [\@src:action/<name>],
  [Automation agent output],
  [\@src:automation/<name>],
)

An explicitly authored source normally wins over automatic stamping. Lifecycle stamps used for connect records, rule conclusions, and action effects are added even when another source is present, because the system must find those rows later for attribution or retraction.

Stamping occurs before the claim key is computed. This intentionally gives different actors separate belief series. Restating a claim with another actor's source context is the explicit way to supersede or retract that actor's series.
