import { test } from 'node:test'
import * as assert from 'node:assert/strict'
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { pathToFileURL } from 'node:url'
import { join } from 'node:path'
import { open } from '@cavelang/store'
import type { Store } from '@cavelang/store'
import { clientFormatVersion, generateClient } from '@cavelang/shape'

const schema = [
  'service EXPECTS owner #cardinality:one',
  'service EXPECTS latency #unit:ms',
  'service EXPECTS USES',
  'team EXPECTS PART-OF #cardinality:one'
]

test('typed client generation is deterministic, sorted, and versioned (spec §20.4)', () => {
  const a = open()
  const b = open()
  a.ingest(schema.join('\n'))
  b.ingest([...schema].reverse().join('\n'))
  const left = generateClient(a)
  const right = generateClient(b)
  assert.equal(left.ok, true)
  assert.equal(right.ok, true)
  if (!left.ok || !right.ok) return
  assert.equal(left.version, clientFormatVersion)
  assert.equal(left.digest, right.digest)
  assert.equal(left.code, right.code)
  assert.match(left.code, /Generated by CAVE typed-client\/v1/)
  assert.match(left.code, /readonly "owner": CaveValue<undefined>/)
  assert.match(left.code, /readonly "latency": readonly CaveValue<"ms">\[\]/)
  assert.match(left.code, /relationValues\(store, entity, "CONTAINS", true\)/)
  a.close()
  b.close()
})

test('generated readers execute against the store and enforce exact-one cardinality', async () => {
  const store = open()
  store.ingest(schema.join('\n'))
  store.ingest([
    'api IS service',
    'api HAS owner: platform',
    'api HAS latency: 20ms',
    'api USES postgres'
  ].join('\n'))
  const generated = generateClient(store)
  assert.equal(generated.ok, true)
  if (!generated.ok) return
  const dir = mkdtempSync(join(process.cwd(), 'test/generated-client-'))
  const path = join(dir, 'client.ts')
  try {
    writeFileSync(path, generated.code)
    const client = await import(pathToFileURL(path).href) as {
      readService(store: Store, entity: string): {
        owner: { text: string }, latency: readonly { text: string, unit: string }[], USES: readonly string[]
      }
    }
    const api = client.readService(store, 'api')
    assert.equal(api.owner.text, 'platform')
    assert.deepEqual(api.latency.map(value => ({ ...value })), [{ text: '20ms', number: 20, unit: 'ms' }])
    assert.deepEqual(api.USES, ['postgres'])
    store.ingest('bad IS service\nbad HAS owner: platform\nbad HAS latency: 1s')
    assert.throws(() => client.readService(store, 'bad'), /expected unit ms/)
    store.ingest('api HAS owner: security @src:review')
    assert.throws(() => client.readService(store, 'api'), /expected exactly one value, got 2/)
  } finally {
    rmSync(dir, { recursive: true, force: true })
    store.close()
  }
})

test('schema changes deterministically change generated clients', () => {
  const store = open()
  store.ingest('service EXPECTS owner')
  const before = generateClient(store)
  store.ingest('service EXPECTS repo')
  const after = generateClient(store)
  assert.ok(before.ok && after.ok)
  if (!before.ok || !after.ok) return
  assert.notEqual(after.digest, before.digest)
  assert.doesNotMatch(before.code, /"repo"/)
  assert.match(after.code, /readonly "repo"/)
  store.ingest('service EXPECTS repo @ 0%')
  const retracted = generateClient(store)
  assert.ok(retracted.ok)
  if (retracted.ok) assert.equal(retracted.digest, before.digest)
  store.close()
})

test('unsupported and ambiguous expectations fail with all actionable problems', () => {
  const store = open()
  store.ingest([
    'service EXPECTS owner #cardinality:many',
    'service EXPECTS USES #unit:ms',
    'api-service EXPECTS repo',
    'api/service EXPECTS owner',
    'team EXPECTS PART-OF #cardinality:one @src:a',
    'team EXPECTS PART-OF @src:b'
  ].join('\n'))
  const result = generateClient(store)
  assert.equal(result.ok, false)
  if (result.ok) return
  assert.match(result.problems.join('\n'), /cardinality must be one or some/)
  assert.match(result.problems.join('\n'), /relation expectations cannot declare #unit/)
  assert.match(result.problems.join('\n'), /both generate ApiService/)
  assert.match(result.problems.join('\n'), /conflicting current declarations/)
  assert.deepEqual(generateClient(store, { version: 2 }), {
    ok: false,
    problems: ['unsupported typed-client format version 2; supported: 1']
  })
  store.close()
})
